# https://github.com/marketplace/actions/auto-message-for-pr-s-and-issues
name: Auto message for PR's and Issues
description: Automatically send hello message to the first PR and Issue for new contributor.
branding:
  icon: message-square
  color: yellow
on: [pull_request, issues]
jobs:
  greeting:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "Hello, thank you for opening your Pull Request ! ğŸ‘"
        issue-message: "Hello @${{ github.actor }} , thank you for submitting your first Issue ! ğŸ™‚"
