# https://github.com/marketplace/actions/auto-message-for-pr-s-and-issues
name: Auto message for PR's and Issues
on: [pull_request_target, issues]
jobs:
  greeting:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Hello @${{ github.actor }} , thank you for submitting a pull request! ğŸ™‚'
        issue-message: 'Hello @${{ github.actor }} , thank you for submitting an issue! ğŸ‘'
